### ISSUE TITLE
Iam getting issue while connecting to the wallet in ios devices same code is working in android devices.

### ISSUE THREAD

**Issue by codewithnazim** [phantom/docs#50]
We are trying to connect a webpage with the Mobile phone phantom wallet app, everything is working fine for Android devices 
but the detection of iPhone is not working, when I am clicking on the wallet button in ios it is redirecting to the phantom webpage even though I am not getting any error message. Please help me in fixing the issue

**Comment by faisalKhan-99** [comment]
show your code
