### ISSUE TITLE
Feature Request: Custom URLs

### ISSUE THREAD

**Issue by 0x1100010010** [phantom/docs#6]
Hi @chriskalani @rawfalafel , great work on this project. 

Kindly allow users to add **Custom Cluster URLs** i.e. `HTTP://192.x.x.x:8899` etc. Much needed feature for devs, thank you. 
Let me know if you need a hand.

**Comment by fragosti** [comment]
We've added a localhost option. Is that not enough?

**Comment by atrinitytv** [comment]
> We've added a localhost option. Is that not enough?

It would be very nice to specify our own RPC provider.
